version: '3'
services:
  server:
    image: reimashi/my-web:latest
    environment:
      TZ: "Europe/Madrid"
      HTTP_PORT: "8080"
      GITHUB_TOKEN: ""
    restart: always
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:aitorgf.com,www.aitorgf.com"
      traefik.frontend.entryPoints: "http,https"
      traefik.default.protocol: "https"
      traefik.docker.network: "intranet"
    networks:
      - intranet
      - internet
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REPO_USER: "reimashi"
      REPO_PASS: ""
    command: --interval 300
networks:
  intranet:
    external:
      name: intranet
  internet:
    external:
      name: internet
