version: '3'
services:
  server:
    image: reimashi/my-web:latest
    environment:
      TZ: "Europe/Madrid"
      HTTP_PORT: "8080"
      GITHUB_TOKEN: ""
    restart: always
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:aitorgf.com,www.aitorgf.com"
      traefik.frontend.entryPoints: "http,https"
      traefik.default.protocol: "https"
      traefik.docker.network: "intranet"
    networks:
      - intranet
      - internet
networks:
  intranet:
    external:
      name: intranet
  internet:
    external:
      name: internet
