name: miweb_server
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
#author: reima <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^1.3.0
  shelf: ^0.7.0
  crossroad:
    git: https://github.com/reimashi/crossroad.git
  shelf_static: ^0.2.7
  github: "^3.0.0"
  shelf_cors: ">0.1.0"

dev_dependencies:
